format_version: 10
pipelines:
  Deploy_Conversions:
    group: My-Pipelines
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      ConversionServiceMaster:
        git: git@github.com:gerhardvanwyk/conversion.git
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - Build:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          maven_build:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - clean
                - install
                command: mvn
                run_if: passed
